### ISSUE TITLE
Cant upload any images anymore

### ISSUE THREAD

**Issue by Tobias-Keller** [rosell-dk/webp-express#306]
Since the last update we cant upload any image...here is the fatal error from the wordpress debug.log.

Debug Log:
`[23-Jul-2019 08:06:15 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php:25
Stack trace:
#0 /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BaseLogger.php(41): WebPConvert\Loggers\BufferLogger->log('', '')
#1 /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/LoggerTrait.php(42): WebPConvert\Loggers\BaseLogger->logLn('', '')
#2 /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php(78): WebPConvert\Convert\Converters\AbstractConverter->logLn('')
#3 [internal function]: WebPConvert\Convert\Converters\AbstractConverter->warningHandler(2, 'file_exists(): ...', '/var/www/vhosts...', 385)
#4 /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/ve in /var/www/vhosts/bcis.de/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php on line 25
`

**Comment by Tobias-Keller** [comment]
Also some old PDF redirections not working if the plugin is enabled

**Comment by rosell-dk** [comment]
First and foremost, there is a recursion issue. The error handler calls itself which calls itself.
This can be avoided by changing the following in `plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php`:

Replace these lines (line 84-88):
```php
        if (!is_null($this->previousErrorHandler)) {
            return call_user_func($this->previousErrorHandler, $errno, $errstr, $errfile, $errline);
        } else {
            return false;
        }
```

with these:
```php
        if (!is_null($this->previousErrorHandler)) {
            // If previousErrorHandler is this very error handler, exit to avoid recursion
            // (this could happen if ::activateWarningLogger() were called twice)
            if (
                is_array($this->previousErrorHandler) &&
                isset($this->previousErrorHandler[0]) &&
                ($this->previousErrorHandler[0] == $this)
            ) {
                return false;
            } else {
                return call_user_func($this->previousErrorHandler, $errno, $errstr, $errfile, $errline);
            }
        } else {
            return false;
        }
```

Can you check to see if this completely solves the issue? - thanks

**Comment by Tobias-Keller** [comment]
Seems not to taken effect

`[02-Aug-2019 12:51:16 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php:25
Stack trace:
#0 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BaseLogger.php(41): WebPConvert\Loggers\BufferLogger->log('', '')
#1 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/LoggerTrait.php(42): WebPConvert\Loggers\BaseLogger->logLn('', '')
#2 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php(78): WebPConvert\Convert\Converters\AbstractConverter->logLn('')
#3 [internal function]: WebPConvert\Convert\Converters\AbstractConverter->warningHandler(2, 'file_exists(): ...', '/var/www/vhosts...', 385)
#4 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/ve in /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php on line 25
[02-Aug-2019 12:51:32 UTC] PHP Warning:  unlink(/var/www/vhosts/site/httpdocs/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/08/beach-salt-water-sand-17727.png.webp): No such file or directory in /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/lib/classes/HandleDeleteFileHook.php on line 24
[02-Aug-2019 12:51:32 UTC] PHP Stack trace:
[02-Aug-2019 12:51:32 UTC] PHP   1. {main}() /var/www/vhosts/site/httpdocs/wp-admin/admin-ajax.php:0
[02-Aug-2019 12:51:32 UTC] PHP   2. do_action() /var/www/vhosts/site/httpdocs/wp-admin/admin-ajax.php:173
[02-Aug-2019 12:51:32 UTC] PHP   3. WP_Hook->do_action() /var/www/vhosts/site/httpdocs/wp-includes/plugin.php:465
[02-Aug-2019 12:51:32 UTC] PHP   4. WP_Hook->apply_filters() /var/www/vhosts/site/httpdocs/wp-includes/class-wp-hook.php:310
[02-Aug-2019 12:51:32 UTC] PHP   5. wp_ajax_delete_post() /var/www/vhosts/site/httpdocs/wp-includes/class-wp-hook.php:286
[02-Aug-2019 12:51:32 UTC] PHP   6. wp_delete_post() /var/www/vhosts/site/httpdocs/wp-admin/includes/ajax-actions.php:816
[02-Aug-2019 12:51:32 UTC] PHP   7. wp_delete_attachment() /var/www/vhosts/site/httpdocs/wp-includes/post.php:2788
[02-Aug-2019 12:51:32 UTC] PHP   8. wp_delete_attachment_files() /var/www/vhosts/site/httpdocs/wp-includes/post.php:5450
[02-Aug-2019 12:51:32 UTC] PHP   9. wp_delete_file_from_directory() /var/www/vhosts/site/httpdocs/wp-includes/post.php:5518
[02-Aug-2019 12:51:32 UTC] PHP  10. wp_delete_file() /var/www/vhosts/site/httpdocs/wp-includes/functions.php:6304
[02-Aug-2019 12:51:32 UTC] PHP  11. apply_filters() /var/www/vhosts/site/httpdocs/wp-includes/functions.php:6268
[02-Aug-2019 12:51:32 UTC] PHP  12. WP_Hook->apply_filters() /var/www/vhosts/site/httpdocs/wp-includes/plugin.php:208
[02-Aug-2019 12:51:32 UTC] PHP  13. WebPExpress\HandleDeleteFileHook::deleteAssociatedWebP() /var/www/vhosts/site/httpdocs/wp-includes/class-wp-hook.php:286
[02-Aug-2019 12:51:32 UTC] PHP  14. unlink() /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/lib/classes/HandleDeleteFileHook.php:24
[02-Aug-2019 12:51:32 UTC] WebP Express failed deleting webp:/var/www/vhosts/site/httpdocs/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2019/08/beach-salt-water-sand-17727.png.webp
[02-Aug-2019 12:51:50 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php:25
Stack trace:
#0 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BaseLogger.php(41): WebPConvert\Loggers\BufferLogger->log('', '')
#1 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/LoggerTrait.php(42): WebPConvert\Loggers\BaseLogger->logLn('', '')
#2 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php(78): WebPConvert\Convert\Converters\AbstractConverter->logLn('')
#3 [internal function]: WebPConvert\Convert\Converters\AbstractConverter->warningHandler(2, 'file_exists(): ...', '/var/www/vhosts...', 385)
#4 /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/ve in /var/www/vhosts/site/httpdocs/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Loggers/BufferLogger.php on line 25
`

**Comment by rosell-dk** [comment]
Hm. Strange.

Can you try to comment out this line in the same file, just to make sure that it is that line that generates the endless recursion.
Replace the following line in `plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php`:

```php
  return call_user_func($this->previousErrorHandler, $errno, $errstr, $errfile, $errline);
```
with this:
```php
   // return call_user_func($this->previousErrorHandler, $errno, $errstr, $errfile, $errline);
```

After that, I expect that there will no longer be generated a "PHP Fatal error: Uncaught Error: Maximum function nesting level of '256' reached, aborting!" error (and you should be able to upload).
Of course, this "fix" will kill functionality. So it is not going to be the fix. I just need to know if this line is the root of the cause.

Also, as I see from your log that there is another warning, which is triggered when a file is deleted, can you replace the following lines in `plugins/webp-express/lib/classes/HandleDeleteFileHook.php` (line 24-26):

```php
          if (!unlink($destination)) {
              error_log('WebP Express failed deleting webp:' . $destination);
          }            
```

with these:
```php
        if (@file_exists($destination)) {
            if (!@unlink($destination)) {
                error_log('WebP Express failed deleting webp:' . $destination);
            }            
        }
```

Thanks

**Comment by Tobias-Keller** [comment]
Wit that changes there is no error or warning anymore....
